// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiTC3P4-HGnXOhtcs7Kv8__2dqlH2-mVw',
    appId: '1:406575607737:web:8781be5db949a1ccf5d068',
    messagingSenderId: '406575607737',
    projectId: 'auctioneer-6b9f2',
    authDomain: 'auctioneer-6b9f2.firebaseapp.com',
    storageBucket: 'auctioneer-6b9f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVJnV_4v7wylax0vaMR8rQGzAPZjGmsHI',
    appId: '1:406575607737:android:3082ef8295c6474ff5d068',
    messagingSenderId: '406575607737',
    projectId: 'auctioneer-6b9f2',
    storageBucket: 'auctioneer-6b9f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGDdCT0VFHTO92eURMzK3R9_hHC75ERI',
    appId: '1:406575607737:ios:145188963d66e50bf5d068',
    messagingSenderId: '406575607737',
    projectId: 'auctioneer-6b9f2',
    storageBucket: 'auctioneer-6b9f2.appspot.com',
    iosClientId: '406575607737-j032vejej9f9iu8outhaska8sk7aean6.apps.googleusercontent.com',
    iosBundleId: 'com.example.auction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjGDdCT0VFHTO92eURMzK3R9_hHC75ERI',
    appId: '1:406575607737:ios:145188963d66e50bf5d068',
    messagingSenderId: '406575607737',
    projectId: 'auctioneer-6b9f2',
    storageBucket: 'auctioneer-6b9f2.appspot.com',
    iosClientId: '406575607737-j032vejej9f9iu8outhaska8sk7aean6.apps.googleusercontent.com',
    iosBundleId: 'com.example.auction',
  );
}
